const doc = {
  _id: 'DBNAME',
  User: 'user',
  Config: 'config',
  Miscellaneous: 'miscellaneous',
  Location: 'location',
  Grouping: 'grouping',
  SevGroup: 'sevgroup',
  Question: 'question',
  QUAReq: 'quareq',
  APProc: 'approc',
  DOCReq: 'docreq',
  ENTReq: 'entreq',
  Footnote: 'footnote',
  Tips: 'tip',
  IconDocs: 'icondocs',
  QFlow: 'qflow',
  QOrder: 'qorder',
  ArrivalAns: 'arrivalans',
  DefaultQ: 'defaultq',
  TransitAnsComp: 'transitanscomp',
  TransitAnsTemp: 'transitanstemp',
  DepartAnsTemp: 'departanstemp',
  DepartAnsComp: 'departanscomp',
  DepartAnsLoc: 'departansloc',
  DepartAnsTest: 'departanstest',
  DepartAnsLink: 'departanslink',
  UserRec: 'xuserrecord',
};

module.exports = doc;